"""Deterministic sample market data provider for previews and tests."""

from __future__ import annotations

from datetime import datetime, timedelta

from server.firemoney_server.domain.one_to_two_types import (
    FundamentalSnapshot,
    HistoricalPriceBar,
    IntradayPriceBar,
    MarketTrendRow,
    OneToTwoMarketRow,
    TickSnapshot,
)
from shared.contracts import MainlineNewsItem


class SampleMarketDataProvider:
    """Deterministic one-to-two sample data for preview and tests."""

    def load_one_to_two_rows(self, trade_date: str) -> tuple[OneToTwoMarketRow, ...]:
        if trade_date == "2026-05-12":
            return (
                OneToTwoMarketRow(
                    symbol="600001",
                    name="北辰科技",
                    trade_date=trade_date,
                    board="涓绘澘",
                    is_st=False,
                    is_delisting=False,
                    listing_days=1200,
                    latest_price=10.12,
                    previous_close=9.56,
                    limit_up_price=10.52,
                    first_limit_up_time="10:22",
                    sealed_amount=12000000,
                    turnover_amount=180000000,
                    turnover_rate=3.8,
                    open_pct=0.018,
                    auction_amount=6000000,
                    low_20=8.8,
                    high_60=10.6,
                    pressure_price=11.8,
                    ma_5=9.92,
                    ma_10=9.81,
                    ma_20=9.34,
                    recent_gain_pct=0.12,
                    theme="AI绔晶涓荤嚎",
                    market_temperature=58,
                    first_board_count=45,
                    volume_ratio_5=1.15,
                    rsi_14=61.0,
                    position_percentile_60=0.69,
                    market_cap=12_000_000_000,
                    float_market_cap=8_500_000_000,
                ),
                OneToTwoMarketRow(
                    symbol="600011",
                    name="龙翼智能",
                    trade_date=trade_date,
                    board="涓绘澘",
                    is_st=False,
                    is_delisting=False,
                    listing_days=1800,
                    latest_price=18.1,
                    previous_close=17.0,
                    limit_up_price=18.7,
                    first_limit_up_time="10:38",
                    sealed_amount=11000000,
                    turnover_amount=210000000,
                    turnover_rate=4.8,
                    open_pct=0.024,
                    auction_amount=6500000,
                    low_20=16.0,
                    high_60=19.0,
                    pressure_price=21.2,
                    ma_5=17.7,
                    ma_10=17.1,
                    ma_20=16.8,
                    recent_gain_pct=0.18,
                    theme="AI绔晶涓荤嚎",
                    market_temperature=58,
                    first_board_count=45,
                    volume_ratio_5=1.18,
                    rsi_14=63.0,
                    position_percentile_60=0.71,
                    market_cap=79_000_000_000,
                    float_market_cap=62_000_000_000,
                ),
            )
        return (
            OneToTwoMarketRow(
                symbol="600001",
                name="北辰科技",
                trade_date=trade_date,
                board="主板",
                is_st=False,
                is_delisting=False,
                listing_days=1200,
                latest_price=10.52,
                previous_close=9.56,
                limit_up_price=10.52,
                first_limit_up_time="09:48",
                sealed_amount=36000000,
                turnover_amount=320000000,
                turnover_rate=6.2,
                open_pct=0.035,
                auction_amount=12000000,
                low_20=8.8,
                high_60=10.6,
                pressure_price=11.8,
                ma_5=10.0,
                ma_10=9.7,
                ma_20=9.2,
                recent_gain_pct=0.18,
                theme="AI端侧主线",
                market_temperature=74,
                first_board_count=45,
                volume_ratio_5=1.6,
                rsi_14=68.0,
                position_percentile_60=0.78,
                market_cap=12_800_000_000,
                float_market_cap=8_600_000_000,
            ),
            OneToTwoMarketRow(
                symbol="600007",
                name="海川智造",
                trade_date=trade_date,
                board="主板",
                is_st=False,
                is_delisting=False,
                listing_days=1400,
                latest_price=12.1,
                previous_close=11.0,
                limit_up_price=12.1,
                first_limit_up_time="10:18",
                sealed_amount=26000000,
                turnover_amount=210000000,
                turnover_rate=5.6,
                open_pct=0.026,
                auction_amount=7000000,
                low_20=10.6,
                high_60=12.2,
                pressure_price=13.7,
                ma_5=11.6,
                ma_10=11.2,
                ma_20=10.9,
                recent_gain_pct=0.16,
                theme="AI端侧主线",
                market_temperature=74,
                first_board_count=45,
                volume_ratio_5=1.4,
                rsi_14=66.0,
                position_percentile_60=0.72,
                market_cap=18_000_000_000,
                float_market_cap=9_200_000_000,
            ),
            OneToTwoMarketRow(
                symbol="600008",
                name="云程数据",
                trade_date=trade_date,
                board="主板",
                is_st=False,
                is_delisting=False,
                listing_days=1500,
                latest_price=13.2,
                previous_close=12.0,
                limit_up_price=13.2,
                first_limit_up_time="10:02",
                sealed_amount=28000000,
                turnover_amount=220000000,
                turnover_rate=5.2,
                open_pct=0.034,
                auction_amount=7500000,
                low_20=11.0,
                high_60=13.4,
                pressure_price=15.0,
                ma_5=12.7,
                ma_10=12.1,
                ma_20=11.4,
                recent_gain_pct=0.18,
                theme="AI端侧主线",
                market_temperature=74,
                first_board_count=45,
                volume_ratio_5=1.5,
                rsi_14=67.0,
                position_percentile_60=0.74,
                market_cap=52_000_000_000,
                float_market_cap=36_000_000_000,
            ),
            OneToTwoMarketRow(
                symbol="600009",
                name="星河通信",
                trade_date=trade_date,
                board="主板",
                is_st=False,
                is_delisting=False,
                listing_days=1300,
                latest_price=9.9,
                previous_close=9.0,
                limit_up_price=9.9,
                first_limit_up_time="10:12",
                sealed_amount=24000000,
                turnover_amount=210000000,
                turnover_rate=4.9,
                open_pct=0.028,
                auction_amount=9000000,
                low_20=8.3,
                high_60=10.0,
                pressure_price=11.4,
                ma_5=9.5,
                ma_10=9.1,
                ma_20=8.7,
                recent_gain_pct=0.15,
                theme="AI端侧主线",
                market_temperature=74,
                first_board_count=45,
                volume_ratio_5=1.3,
                rsi_14=64.0,
                position_percentile_60=0.7,
                market_cap=46_000_000_000,
                float_market_cap=21_000_000_000,
            ),
            OneToTwoMarketRow(
                symbol="600010",
                name="东岳互联",
                trade_date=trade_date,
                board="主板",
                is_st=False,
                is_delisting=False,
                listing_days=1600,
                latest_price=15.4,
                previous_close=14.0,
                limit_up_price=15.4,
                first_limit_up_time="10:26",
                sealed_amount=33000000,
                turnover_amount=230000000,
                turnover_rate=6.8,
                open_pct=0.021,
                auction_amount=8000000,
                low_20=13.4,
                high_60=15.6,
                pressure_price=17.6,
                ma_5=14.9,
                ma_10=14.3,
                ma_20=13.8,
                recent_gain_pct=0.2,
                theme="AI端侧主线",
                market_temperature=74,
                first_board_count=45,
                volume_ratio_5=1.7,
                rsi_14=70.0,
                position_percentile_60=0.8,
                market_cap=78_000_000_000,
                float_market_cap=44_000_000_000,
            ),
            OneToTwoMarketRow(
                symbol="600011",
                name="龙翼智能",
                trade_date=trade_date,
                board="主板",
                is_st=False,
                is_delisting=False,
                listing_days=1800,
                latest_price=18.7,
                previous_close=17.0,
                limit_up_price=18.7,
                first_limit_up_time="10:28",
                sealed_amount=36000000,
                turnover_amount=230000000,
                turnover_rate=7.1,
                open_pct=0.033,
                auction_amount=8000000,
                low_20=16.0,
                high_60=19.0,
                pressure_price=21.2,
                ma_5=18.0,
                ma_10=17.4,
                ma_20=16.7,
                recent_gain_pct=0.22,
                theme="AI端侧主线",
                market_temperature=74,
                first_board_count=45,
                volume_ratio_5=1.8,
                rsi_14=72.0,
                position_percentile_60=0.82,
                market_cap=79_000_000_000,
                float_market_cap=63_000_000_000,
            ),
            OneToTwoMarketRow(
                symbol="600002",
                name="金岭高科",
                trade_date=trade_date,
                board="主板",
                is_st=False,
                is_delisting=False,
                listing_days=900,
                latest_price=16.5,
                previous_close=15.0,
                limit_up_price=16.5,
                first_limit_up_time="09:40",
                sealed_amount=18000000,
                turnover_amount=120000000,
                turnover_rate=8.5,
                open_pct=0.085,
                auction_amount=9000000,
                low_20=9.2,
                high_60=16.8,
                pressure_price=17.0,
                ma_5=15.2,
                ma_10=13.6,
                ma_20=12.0,
                recent_gain_pct=0.52,
                theme="高位加速",
                market_temperature=74,
                first_board_count=45,
                volume_ratio_5=2.5,
                rsi_14=91.0,
                position_percentile_60=0.96,
                market_cap=22_000_000_000,
                float_market_cap=15_000_000_000,
            ),
            OneToTwoMarketRow(
                symbol="300003",
                name="迅驰软件",
                trade_date=trade_date,
                board="创业板",
                is_st=False,
                is_delisting=False,
                listing_days=800,
                latest_price=22.0,
                previous_close=20.0,
                limit_up_price=24.0,
                first_limit_up_time="10:20",
                sealed_amount=22000000,
                turnover_amount=160000000,
                turnover_rate=5.1,
                open_pct=0.03,
                auction_amount=8000000,
                low_20=18.0,
                high_60=23.0,
                pressure_price=25.0,
                ma_5=21.0,
                ma_10=20.5,
                ma_20=19.5,
                recent_gain_pct=0.16,
                theme="非主板",
                market_temperature=74,
                first_board_count=45,
                volume_ratio_5=1.5,
                rsi_14=65.0,
                position_percentile_60=0.75,
                market_cap=18_000_000_000,
                float_market_cap=11_000_000_000,
            ),
            OneToTwoMarketRow(
                symbol="600004",
                name="安泰材料",
                trade_date=trade_date,
                board="主板",
                is_st=False,
                is_delisting=False,
                listing_days=1000,
                latest_price=8.8,
                previous_close=8.0,
                limit_up_price=8.8,
                first_limit_up_time="11:12",
                sealed_amount=3000000,
                turnover_amount=130000000,
                turnover_rate=4.1,
                open_pct=0.015,
                auction_amount=3500000,
                low_20=7.4,
                high_60=8.9,
                pressure_price=10.2,
                ma_5=8.4,
                ma_10=8.1,
                ma_20=7.9,
                recent_gain_pct=0.14,
                market_cap=3_800_000_000,
                float_market_cap=2_400_000_000,
                theme="同题材跟风",
                market_temperature=74,
                first_board_count=45,
                volume_ratio_5=0.8,
                rsi_14=52.0,
                position_percentile_60=0.5,
            ),
        )

    def load_mainline_news(
        self,
        theme: str,
        symbols: tuple[str, ...],
    ) -> tuple[MainlineNewsItem, ...]:
        name_map = {
            row.symbol: row.name
            for row in self.load_one_to_two_rows("2026-04-30")
        }
        symbol_text = "、".join(
            f"{name_map.get(symbol, symbol)}（{symbol}）"
            for symbol in symbols[:3]
        )
        return (
            MainlineNewsItem(
                title=f"{theme} 继续获得资金关注，核心候选 {symbol_text} 进入观察",
                source="sample",
                published_at="09:20",
                related_symbols=symbols[:3],
            ),
            MainlineNewsItem(
                title=f"{theme} 分歧中仍有涨停样本，需结合封板质量确认持续性",
                source="sample",
                published_at="10:30",
                related_symbols=symbols[:3],
            ),
        )

    def load_full_market_rows(self, trade_date: str) -> tuple[MarketTrendRow, ...]:
        return (
            MarketTrendRow(
                symbol="603256",
                name="宏和科技",
                trade_date=trade_date,
                board="主板",
                latest_price=12.18,
                previous_close=11.86,
                change_pct=2.7,
                turnover_amount=680_000_000,
                turnover_rate=7.8,
                market_cap=10_800_000_000,
                float_market_cap=8_900_000_000,
                industry="电子布 PCB",
                theme="AI服务器PCB上游电子布",
            ),
            MarketTrendRow(
                symbol="300502",
                name="新易盛",
                trade_date=trade_date,
                board="创业板",
                latest_price=97.6,
                previous_close=94.3,
                change_pct=3.5,
                turnover_amount=3_900_000_000,
                turnover_rate=8.6,
                market_cap=71_000_000_000,
                float_market_cap=61_000_000_000,
                industry="通信设备",
                theme="AI算力 CPO 光模块",
            ),
            MarketTrendRow(
                symbol="600011",
                name="龙翼智能",
                trade_date=trade_date,
                board="主板",
                latest_price=18.7,
                previous_close=18.3,
                change_pct=2.2,
                turnover_amount=520_000_000,
                turnover_rate=5.4,
                market_cap=22_000_000_000,
                float_market_cap=14_000_000_000,
                industry="机器人",
                theme="具身智能机器人",
            ),
            MarketTrendRow(
                symbol="600004",
                name="安泰材料",
                trade_date=trade_date,
                board="主板",
                latest_price=8.8,
                previous_close=8.72,
                change_pct=0.9,
                turnover_amount=90_000_000,
                turnover_rate=2.1,
                market_cap=3_800_000_000,
                float_market_cap=2_400_000_000,
                industry="材料",
                theme="同题材跟风",
            ),
            MarketTrendRow(
                symbol="600002",
                name="金岭高科",
                trade_date=trade_date,
                board="主板",
                latest_price=16.5,
                previous_close=15.0,
                change_pct=10.0,
                turnover_amount=1_400_000_000,
                turnover_rate=17.0,
                market_cap=22_000_000_000,
                float_market_cap=15_000_000_000,
                industry="半导体",
                theme="高位加速",
            ),
            MarketTrendRow(
                symbol="688888",
                name="晶桥半导",
                trade_date=trade_date,
                board="科创板",
                latest_price=41.2,
                previous_close=40.9,
                change_pct=0.7,
                turnover_amount=760_000_000,
                turnover_rate=4.2,
                market_cap=28_000_000_000,
                float_market_cap=13_000_000_000,
                industry="半导体材料",
                theme="先进封装材料",
            ),
        )

    def load_fundamental_snapshot(self, symbol: str) -> FundamentalSnapshot | None:
        snapshots = {
            "603256": FundamentalSnapshot(
                symbol="603256",
                name="宏和科技",
                report_date="2026Q1",
                roe_pct=8.4,
                revenue_growth_pct=18.0,
                net_profit_growth_pct=42.0,
                gross_margin_pct=28.5,
                debt_ratio_pct=32.0,
                pe_ttm=38.0,
                pb=3.2,
                summary="sample",
            ),
            "300502": FundamentalSnapshot(
                symbol="300502",
                name="新易盛",
                report_date="2026Q1",
                roe_pct=19.5,
                revenue_growth_pct=58.0,
                net_profit_growth_pct=96.0,
                gross_margin_pct=43.0,
                debt_ratio_pct=18.0,
                pe_ttm=47.0,
                pb=9.6,
                summary="sample",
            ),
            "600011": FundamentalSnapshot(
                symbol="600011",
                name="龙翼智能",
                report_date="2026Q1",
                roe_pct=6.8,
                revenue_growth_pct=12.0,
                net_profit_growth_pct=15.0,
                gross_margin_pct=24.0,
                debt_ratio_pct=45.0,
                pe_ttm=52.0,
                pb=3.8,
                summary="sample",
            ),
            "688888": FundamentalSnapshot(
                symbol="688888",
                name="晶桥半导",
                report_date="2026Q1",
                roe_pct=9.8,
                revenue_growth_pct=31.0,
                net_profit_growth_pct=36.0,
                gross_margin_pct=35.0,
                debt_ratio_pct=28.0,
                pe_ttm=44.0,
                pb=4.5,
                summary="sample",
            ),
        }
        return snapshots.get(symbol)

    def load_price_bars(
        self,
        symbol: str,
        start_date: str,
        end_date: str,
    ) -> tuple[HistoricalPriceBar, ...]:
        generated = self._generated_price_bars(symbol, end_date)
        if generated:
            return tuple(
                bar for bar in generated if start_date <= bar.trade_date <= end_date
            )
        sample_bars = {
            "600001": (
                HistoricalPriceBar(
                    trade_date="2026-04-30",
                    open_price=10.52,
                    high_price=10.52,
                    low_price=10.20,
                    close_price=10.52,
                    volume=1200000,
                    amount=12624000,
                ),
                HistoricalPriceBar(
                    trade_date="2026-05-06",
                    open_price=10.88,
                    high_price=11.38,
                    low_price=10.72,
                    close_price=11.20,
                    volume=1800000,
                    amount=20160000,
                ),
                HistoricalPriceBar(
                    trade_date="2026-05-07",
                    open_price=11.18,
                    high_price=11.50,
                    low_price=10.94,
                    close_price=11.36,
                    volume=1500000,
                    amount=17040000,
                ),
                HistoricalPriceBar(
                    trade_date="2026-05-08",
                    open_price=11.30,
                    high_price=11.42,
                    low_price=10.98,
                    close_price=11.05,
                    volume=1300000,
                    amount=14365000,
                ),
            )
        }
        bars = sample_bars.get(symbol, ())
        return tuple(
            bar for bar in bars if start_date <= bar.trade_date <= end_date
        )

    def _generated_price_bars(
        self,
        symbol: str,
        end_date: str,
    ) -> tuple[HistoricalPriceBar, ...]:
        specs = {
            "603256": (7.8, 12.18, 0.12, 680_000_000),
            "300502": (42.0, 97.6, 0.34, 3_900_000_000),
            "600011": (12.8, 18.7, 0.18, 520_000_000),
            "600002": (7.0, 16.5, 0.42, 1_400_000_000),
            "688888": (26.0, 41.2, 0.16, 760_000_000),
        }
        spec = specs.get(symbol)
        if spec is None:
            return ()
        start_price, end_price, wave, latest_amount = spec
        try:
            end = datetime.strptime(end_date, "%Y-%m-%d").date()
        except ValueError:
            return ()
        bars: list[HistoricalPriceBar] = []
        total_days = 130
        for index in range(total_days):
            trade_date = (end - timedelta(days=total_days - index - 1)).isoformat()
            progress = index / (total_days - 1)
            trend = start_price + (end_price - start_price) * progress
            cycle = ((index % 17) - 8) / 8 * wave
            close = max(1.0, trend * (1 + cycle * 0.08))
            if symbol == "300502" and index > 105:
                close *= 1 + (index - 105) * 0.01
            if symbol == "600002" and index > 100:
                close *= 1 + (index - 100) * 0.018
            if index == total_days - 1:
                close = end_price
            open_price = close * (0.99 + (index % 5) * 0.004)
            high = max(open_price, close) * 1.025
            low = min(open_price, close) * 0.975
            amount_base = latest_amount * (0.55 + progress * 0.35)
            if index == total_days - 1:
                amount = latest_amount
            else:
                amount = amount_base * (0.9 + (index % 9) * 0.03)
            bars.append(
                HistoricalPriceBar(
                    trade_date=trade_date,
                    open_price=round(open_price, 2),
                    high_price=round(high, 2),
                    low_price=round(low, 2),
                    close_price=round(close, 2),
                    volume=round(amount / max(close, 0.01), 0),
                    amount=round(amount, 2),
                )
            )
        return tuple(bars)

    def load_intraday_bars(
        self,
        symbol: str,
        trade_date: str,
        interval_minutes: int = 1,
    ) -> tuple[IntradayPriceBar, ...]:
        if symbol == "600001" and trade_date == "2026-05-12":
            return (
                IntradayPriceBar(
                    trade_date=trade_date,
                    timestamp="09:31",
                    open_price=10.10,
                    high_price=10.14,
                    low_price=10.06,
                    close_price=10.12,
                    volume=86000,
                    amount=870320,
                ),
                IntradayPriceBar(
                    trade_date=trade_date,
                    timestamp="09:32",
                    open_price=10.12,
                    high_price=10.18,
                    low_price=10.11,
                    close_price=10.17,
                    volume=92000,
                    amount=935640,
                ),
            )
        if symbol != "600001" or trade_date != "2026-04-30":
            return ()
        return (
            IntradayPriceBar(
                trade_date=trade_date,
                timestamp="09:31",
                open_price=10.52,
                high_price=10.56,
                low_price=10.49,
                close_price=10.54,
                volume=120000,
                amount=1264800,
            ),
            IntradayPriceBar(
                trade_date=trade_date,
                timestamp="09:32",
                open_price=10.54,
                high_price=10.58,
                low_price=10.53,
                close_price=10.57,
                volume=95000,
                amount=1004150,
            ),
        )

    def load_tick_snapshots(
        self,
        symbol: str,
        trade_date: str,
    ) -> tuple[TickSnapshot, ...]:
        if symbol == "600001" and trade_date == "2026-05-12":
            return (
                TickSnapshot(
                    trade_date=trade_date,
                    timestamp="09:30:08",
                    last_price=10.11,
                    volume=18000,
                    amount=181980,
                    side="buy",
                    bid_price_1=10.10,
                    ask_price_1=10.11,
                    bid_volume_1=76000,
                    ask_volume_1=38000,
                ),
                TickSnapshot(
                    trade_date=trade_date,
                    timestamp="09:30:26",
                    last_price=10.12,
                    volume=36000,
                    amount=364320,
                    side="buy",
                    bid_price_1=10.12,
                    ask_price_1=10.13,
                    bid_volume_1=84000,
                    ask_volume_1=35000,
                ),
            )
        if symbol != "600001" or trade_date != "2026-04-30":
            return ()
        return (
            TickSnapshot(
                trade_date=trade_date,
                timestamp="09:30:05",
                last_price=10.52,
                volume=15000,
                amount=157800,
                side="buy",
                bid_price_1=10.51,
                ask_price_1=10.52,
                bid_volume_1=88000,
                ask_volume_1=42000,
            ),
            TickSnapshot(
                trade_date=trade_date,
                timestamp="09:30:30",
                last_price=10.52,
                volume=36000,
                amount=378720,
                side="buy",
                bid_price_1=10.52,
                ask_price_1=10.53,
                bid_volume_1=92000,
                ask_volume_1=39000,
            ),
        )
